#!/bin/bash

echo "=========================================="
echo "Azure Capstone Deployment Instructions"
echo "=========================================="
echo ""
echo "PowerShell is not installed on this system."
echo ""
echo "Choose one of these options:"
echo ""
echo "OPTION 1: Use Azure Cloud Shell (RECOMMENDED)"
echo "  1. Go to https://portal.azure.com"
echo "  2. Click the Cloud Shell icon (>_)"
echo "  3. Select PowerShell"
echo "  4. Upload these files:"
echo "     - deploy-everything-for-screenshots.ps1"
echo "     - create-custom-role.ps1"
echo "     - deploy-keyvault.ps1"
echo "     - policy-*.json (all 3 policy files)"
echo "  5. Run: ./deploy-everything-for-screenshots.ps1"
echo ""
echo "OPTION 2: Install PowerShell locally"
echo "  1. Install PowerShell:"
echo "     brew install --cask powershell"
echo "  2. Install Azure PowerShell module:"
echo "     pwsh -Command 'Install-Module -Name Az -AllowClobber -Scope CurrentUser'"
echo "  3. Run this script again"
echo ""
echo "OPTION 3: Run deployment manually (step-by-step)"
echo "  See: SCREENSHOT-CAPTURE-GUIDE.md for manual PowerShell commands"
echo ""
echo "=========================================="
